/**
 * Place Model
 * Defines the data structure for storing user saved places in Firestore
 */

/**
 * Place document structure in Firestore
 * Collection: 'places'
 *
 * @typedef {Object} Place
 * @property {string} id - Document ID (auto-generated by Firestore)
 * @property {string} userId - User ID who created the place (required)
 * @property {string} name - Name of the place (e.g., 'Home', 'School') (required)
 * @property {string} type - Type of place (e.g., 'home', 'school', 'work', 'custom') (required)
 * @property {number} latitude - Latitude coordinate (required)
 * @property {number} longitude - Longitude coordinate (required)
 * @property {string} address - Human-readable address (optional)
 * @property {object} location - Location object with type and coordinates (optional)
 * @property {object} metadata - Additional metadata about the place (optional)
 * @property {Date} createdAt - When the record was created
 * @property {Date} updatedAt - When the record was last updated
 */

/**
 * Create a place document object
 * @param {Object} data - Place data
 * @returns {Object} Place document ready for Firestore
 */
export function createPlaceDocument(data) {
  const now = new Date();

  return {
    userId: data.userId || null,
    name: data.name || '',
    type: data.type || 'custom',
    latitude: data.latitude || 0,
    longitude: data.longitude || 0,
    address: data.address || null,
    location: data.location || null,
    metadata: {
      ...(data.metadata || {}),
    },
    createdAt: now,
    updatedAt: now,
  };
}

/**
 * Validate place data before saving
 * @param {Object} data - Place data to validate
 * @returns {Object} Validation result { valid: boolean, errors: string[] }
 */
export function validatePlaceData(data) {
  const errors = [];

  if (!data.userId || typeof data.userId !== 'string') {
    errors.push('UserId is required and must be a string');
  }

  if (!data.name || typeof data.name !== 'string' || data.name.trim().length === 0) {
    errors.push('Name is required and must be a non-empty string');
  }

  if (!data.type || typeof data.type !== 'string') {
    errors.push('Type is required and must be a string');
  }

  const validTypes = ['home', 'school', 'work', 'custom'];
  if (!validTypes.includes(data.type)) {
    errors.push(`Type must be one of: ${validTypes.join(', ')}`);
  }

  if (typeof data.latitude !== 'number' || isNaN(data.latitude)) {
    errors.push('Latitude must be a valid number');
  }

  if (typeof data.longitude !== 'number' || isNaN(data.longitude)) {
    errors.push('Longitude must be a valid number');
  }

  // Validate latitude range (-90 to 90)
  if (data.latitude < -90 || data.latitude > 90) {
    errors.push('Latitude must be between -90 and 90');
  }

  // Validate longitude range (-180 to 180)
  if (data.longitude < -180 || data.longitude > 180) {
    errors.push('Longitude must be between -180 and 180');
  }

  return {
    valid: errors.length === 0,
    errors,
  };
}

/**
 * Transform Firestore document to API response format
 * @param {Object} doc - Firestore document snapshot
 * @returns {Object} Formatted place object
 */
export function formatPlaceResponse(doc) {
  if (!doc.exists) {
    return null;
  }

  const data = doc.data();

  // Convert Firestore Timestamps to ISO strings
  const formatTimestamp = (timestamp) => {
    if (!timestamp) return null;
    if (timestamp.toDate) {
      return timestamp.toDate().toISOString();
    }
    if (timestamp instanceof Date) {
      return timestamp.toISOString();
    }
    return timestamp;
  };

  return {
    id: doc.id,
    ...data,
    createdAt: formatTimestamp(data.createdAt),
    updatedAt: formatTimestamp(data.updatedAt),
  };
}

export default {
  createPlaceDocument,
  validatePlaceData,
  formatPlaceResponse,
};

