/**
 * Sound Model
 * Defines the data structure for storing identified sounds in Firestore
 */

/**
 * Sound document structure in Firestore
 * Collection: 'sounds'
 *
 * @typedef {Object} Sound
 * @property {string} id - Document ID (auto-generated by Firestore)
 * @property {string} userId - User ID who detected/recorded the sound (optional)
 * @property {string} type - Type of sound detected (e.g., 'fire_alarm', 'car_horn', 'dog_barking')
 * @property {number} confidence - Confidence score (0-1)
 * @property {string} timestamp - ISO timestamp when sound was detected
 * @property {string} location - Location where sound was detected (optional)
 * @property {object} context - Additional context information (optional)
 * @property {string} audioFileUrl - URL/path to the audio file (optional)
 * @property {object} metadata - Additional metadata about the sound
 * @property {number} priority - Priority level (if applicable, e.g., for hazards)
 * @property {boolean} isHazard - Whether this sound is classified as a hazard
 * @property {string} status - Status of the sound (e.g., 'detected', 'verified', 'false_positive')
 * @property {Date} createdAt - When the record was created
 * @property {Date} updatedAt - When the record was last updated
 */

/**
 * Create a sound document object
 * @param {Object} data - Sound data
 * @returns {Object} Sound document ready for Firestore
 */
export function createSoundDocument(data) {
  const now = new Date();

  return {
    userId: data.userId || null,
    type: data.type || "unknown",
    confidence: data.confidence || 0,
    timestamp: data.timestamp || now.toISOString(),
    location: data.location || null,
    context: data.context || {},
    audioFileUrl: data.audioFileUrl || null,
    metadata: {
      ...data.metadata,
      sampleRate: data.metadata?.sampleRate || null,
      duration: data.metadata?.duration || null,
      processingTime: data.metadata?.processingTime || null,
    },
    priority: data.priority || null,
    isHazard: data.isHazard || false,
    status: data.status || "detected",
    createdAt: now,
    updatedAt: now,
  };
}

/**
 * Validate sound data before saving
 * @param {Object} data - Sound data to validate
 * @returns {Object} Validation result { valid: boolean, errors: string[] }
 */
export function validateSoundData(data) {
  const errors = [];

  if (!data.type || typeof data.type !== "string") {
    errors.push("Type is required and must be a string");
  }

  if (data.confidence !== undefined) {
    if (
      typeof data.confidence !== "number" ||
      data.confidence < 0 ||
      data.confidence > 1
    ) {
      errors.push("Confidence must be a number between 0 and 1");
    }
  }

  if (data.timestamp && !isValidISOString(data.timestamp)) {
    errors.push("Timestamp must be a valid ISO string");
  }

  return {
    valid: errors.length === 0,
    errors,
  };
}

/**
 * Check if a string is a valid ISO date string
 * @param {string} str - String to check
 * @returns {boolean}
 */
function isValidISOString(str) {
  try {
    const date = new Date(str);
    return (
      date.toISOString() === str ||
      date.toISOString().slice(0, -5) + "Z" === str
    );
  } catch {
    return false;
  }
}

/**
 * Transform Firestore document to API response format
 * @param {Object} doc - Firestore document snapshot
 * @returns {Object} Formatted sound object
 */
export function formatSoundResponse(doc) {
  if (!doc.exists) {
    return null;
  }

  const data = doc.data();

  // Convert Firestore Timestamps to ISO strings
  const formatTimestamp = (timestamp) => {
    if (!timestamp) return null;
    if (timestamp.toDate) {
      return timestamp.toDate().toISOString();
    }
    if (timestamp instanceof Date) {
      return timestamp.toISOString();
    }
    return timestamp;
  };

  return {
    id: doc.id,
    ...data,
    timestamp: formatTimestamp(data.timestamp),
    createdAt: formatTimestamp(data.createdAt),
    updatedAt: formatTimestamp(data.updatedAt),
  };
}

export default {
  createSoundDocument,
  validateSoundData,
  formatSoundResponse,
};
